name: Documentation Check

on:
  push:
    branches: [ develop,cd ]
  pull_request:
    branches: [ develop,cd ]

jobs:
  build-and-publish-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: 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

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade -r requirements.txt
        pip install sphinx
        pip install sphinx_autodoc_typehints
        sudo apt-get install doxygen

    - name: Run Sphinx
      run: |
        cd docsSphinx
        sphinx-apidoc -f -o . ../src/
        make html

    - name: setup git config
      run: |
        git config user.name "GitHub Actions -  building documentation"
        git config user.email "<>"

    - name: commit
      run: |
        git switch -c documentation
        git add documentation/*
        git commit -m "Build new documentation [skip ci]"
        git push origin documentation -f